// ============================================================================
// File: sram_1rw.sv  (syn/lib — synthesis black-box wrapper)
// Project: JV32 RISC-V Processor
//
// Synthesis wrapper: maps the generic sram_1rw interface to the OpenRAM hard
// macro generated by 'make gen-mem' for Nangate FreePDK45.
//
// jv32_top instantiates sram_1rw with exactly one parameter set:
//
//   DEPTH = IRAM_SIZE/4 = 32768  (default 128 KB IRAM or DRAM)
//   WIDTH = 8                    (byte-lane bank)
//
// The OpenRAM compiler produces:
//   sram_1rw_32768x8  —  8 instances total
//                         (4 byte lanes × IRAM, 4 byte lanes × DRAM)
//
// OpenRAM single-port (num_rw_ports=1) pin convention:
//   clk0  – rising-edge clock
//   csb0  – chip-select bar (active-low)
//   web0  – write-enable bar (active-low)
//   addr0 – word address ($clog2(DEPTH) bits)
//   din0  – write data
//   dout0 – read data (registered: valid one cycle after read access)
//
// If IRAM_SIZE or DRAM_SIZE are changed, re-run:
//   make gen-mem [--iram-size N] [--dram-size N]
// and adjust the generate-block below to match the new DEPTH.
// ============================================================================

// This file replaces rtl/memories/sram_1rw.sv in the synthesis RTL file list.

module sram_1rw #(
    parameter int DEPTH = 256,
    parameter int WIDTH = 32
) (
    input  logic                     clk,
    input  logic                     ce,    // chip enable (active-high)
    input  logic                     we,    // write enable (active-high)
    input  logic [$clog2(DEPTH)-1:0] addr,
    input  logic [WIDTH-1:0]         wdata,
    output logic [WIDTH-1:0]         rdata
);

generate

    // -------------------------------------------------------------------------
    // Default TCM byte-lane SRAM: 32768 words × 8 bits
    // Matches jv32_top with IRAM_SIZE=DRAM_SIZE=128 KB
    //   DEPTH = 128*1024/4 = 32768,  WIDTH = 8
    // -------------------------------------------------------------------------
    if (DEPTH == 32768 && WIDTH == 8) begin : g_tcm_byte_sram

        sram_1rw_32768x8 u_mem (
            .clk0 (clk),
            .csb0 (~ce),
            .web0 (~we),
            .addr0(addr),
            .din0 (wdata),
            .dout0(rdata)
        );

    // -------------------------------------------------------------------------
    // Fallback: behavioural register-array model.
    // Caught at synthesis to flag missing OpenRAM macros for new SRAM sizes.
    // -------------------------------------------------------------------------
    end else begin : g_fallback

        // Synthesis tools will warn on $error in a generate block – this is
        // intentional: add a new macro + generate branch for any new size.
        initial $error("sram_1rw: no OpenRAM macro for DEPTH=%0d WIDTH=%0d – run 'make gen-mem'",
                       DEPTH, WIDTH);

        logic [WIDTH-1:0] mem [0:DEPTH-1];

        always_ff @(posedge clk) begin
            if (ce) begin
                if (we) mem[addr] <= wdata;
                else    rdata     <= mem[addr];
            end
        end

    end

endgenerate

endmodule
