# OpenRAM configuration for jv32 TCM 32-bit SRAM
# Generated by gen_openram_config.py – do not edit manually.

import os

# ── SRAM dimensions ──────────────────────────────────────────────────────────
num_words       = 2048
word_size       = 32
write_size      = 8   # byte write enables: wmask0[3:0]
words_per_row   = 1  # 2048 rows, 11-bit decoder

# ── Technology ───────────────────────────────────────────────────────────────
tech_name       = "freepdk45"
nominal_corner_only = False
supply_voltages = [1.1]
temperatures    = [25]

# ── Output ───────────────────────────────────────────────────────────────────
output_name     = "sram_1rw_2048x32"
output_path     = "."
# Generate TT + FF + SS corners for timing sign-off
process_corners = ["TT", "FF", "SS"]

# ── Functional verification ───────────────────────────────────────────────────
check_lvsdrc    = False
