# OpenRAM configuration for jv32 TCM 64-bit SRAM
# Generated by gen_openram_config.py – do not edit manually.

import os

# ── SRAM dimensions ──────────────────────────────────────────────────────────
num_words       = 1024
word_size       = 64
write_size      = 8   # byte write enables: wmask0[7:0]
words_per_row   = 4   # 256 rows, 8-bit column decode; ~2:1 width/height ratio

# ── Technology ───────────────────────────────────────────────────────────────
tech_name       = "freepdk45"
nominal_corner_only = False
supply_voltages = [1.1]
temperatures    = [25]

# ── Output ───────────────────────────────────────────────────────────────────
output_name     = "sram_1rw_1024x64"
output_path     = "."
# Generate TT + FF + SS corners for timing sign-off
process_corners = ["TT", "FF", "SS"]

# ── Functional verification ───────────────────────────────────────────────────
check_lvsdrc    = False
