# OpenRAM configuration for jv32 TCM byte-lane SRAM
# Generated by gen_openram_config.py – do not edit manually.

import os

# ── SRAM dimensions ──────────────────────────────────────────────────────────
num_words       = 32768
word_size       = 8
words_per_row   = 1       # no column mux → minimum bitline length

# ── Technology ───────────────────────────────────────────────────────────────
tech_name       = "freepdk45"
nominal_corner_only = False
supply_voltages = [1.1]
temperatures    = [25]

# ── Output ───────────────────────────────────────────────────────────────────
output_name     = "sram_1rw_32768x8"
output_path     = "."
# Generate TT + FF corners for timing sign-off
process_corners = ["TT", "FF", "SS"]

# ── Functional verification ───────────────────────────────────────────────────
check_lvsdrc    = False
