#!/usr/bin/env python3
"""
gen_openram_config.py – Generate OpenRAM Python config file for jv32 TCM SRAMs.

jv32_top instantiates two byte-banked TCM RAMs (IRAM and DRAM), each implemented
as 4 independent byte-lane SRAMs:

    sram_1rw #(.DEPTH(IRAM_DEPTH), .WIDTH(8)) u_sram[3:0]  // IRAM byte banks
    sram_1rw #(.DEPTH(DRAM_DEPTH), .WIDTH(8)) u_sram[3:0]  // DRAM byte banks

With the default sizes (IRAM_SIZE = DRAM_SIZE = 128 KB):

    DEPTH = IRAM_SIZE / 4 = 32768 words,  WIDTH = 8 bits

Because both RAMs share the same (DEPTH, WIDTH) pair there is a single OpenRAM
macro to compile:  sram_1rw_32768x8

Usage (called by 'make gen-mem'):
    python3 common/gen_openram_config.py \\
        --iram-size 131072 --dram-size 131072 \\
        --pdk freepdk45 --output-dir lib/openram [--optimize speed|area]

Optimization targets
    speed (default) – words_per_row=1 (one bitline pair per word, shortest
                      bitlines) for minimum sense-amp delay, plus FF corner.
    area            – automatic aspect-ratio; TT corner only.
"""

import argparse
import math
import os


def log2(n):
    v = int(round(math.log2(n)))
    assert (1 << v) == n, f"{n} is not a power of 2"
    return v


def make_config(name: str, num_words: int, word_size: int,
                tech_name: str, supply_voltages: list,
                words_per_row_cfg: str, corner_cfg: str,
                process_cfg: str, output_dir: str) -> str:
    """Return the OpenRAM Python config file content for one SRAM."""

    return f"""\
# OpenRAM configuration for jv32 TCM byte-lane SRAM
# Generated by gen_openram_config.py – do not edit manually.

import os

# ── SRAM dimensions ──────────────────────────────────────────────────────────
num_words       = {num_words}
word_size       = {word_size}
{words_per_row_cfg}
# ── Technology ───────────────────────────────────────────────────────────────
tech_name       = "{tech_name}"
nominal_corner_only = False
supply_voltages = {supply_voltages}
temperatures    = [25]
{process_cfg}
# ── Output ───────────────────────────────────────────────────────────────────
output_name     = "{name}"
output_path     = "."
{corner_cfg}
# ── Functional verification ───────────────────────────────────────────────────
check_lvsdrc    = False
"""


def main():
    p = argparse.ArgumentParser(
        description="Generate OpenRAM config for jv32 TCM SRAMs")
    p.add_argument("--iram-size", type=int, default=128 * 1024,
                   help="IRAM total bytes (default: 131072 = 128 KB)")
    p.add_argument("--dram-size", type=int, default=128 * 1024,
                   help="DRAM total bytes (default: 131072 = 128 KB)")
    p.add_argument("--pdk", default="freepdk45",
                   help="PDK name passed to OpenRAM (default: freepdk45)")
    p.add_argument("--output-dir", default="lib/openram",
                   help="Output directory for config files")
    p.add_argument("--optimize", choices=["speed", "area"], default="speed",
                   help="Optimization target (default: speed)")
    args = p.parse_args()

    # jv32_top byte-lane SRAM dimensions
    # Each TCM bank is split into 4 byte-lane SRAMs: DEPTH=SIZE/4, WIDTH=8
    iram_depth = args.iram_size // 4
    dram_depth = args.dram_size // 4
    word_size = 8

    # Sanity check: both must be powers of 2
    log2(iram_depth)
    log2(dram_depth)

    # PDK-specific supply
    if args.pdk == "freepdk45":
        tech_name = "freepdk45"
        supply_voltages = [1.1]
    elif args.pdk == "sky130":
        tech_name = "sky130"
        supply_voltages = [1.8]
    else:
        tech_name = args.pdk
        supply_voltages = [1.8]

    # Optimization settings
    if args.optimize == "speed":
        words_per_row_cfg = "words_per_row   = 1       # no column mux → minimum bitline length\n"
        corner_cfg = "# Generate TT + FF corners for timing sign-off\nprocess_corners = [\"TT\", \"FF\", \"SS\"]\n"
        process_cfg = ""
    else:
        words_per_row_cfg = "# words_per_row auto-selected by OpenRAM for balanced aspect-ratio\n"
        corner_cfg = "process_corners = [\"TT\"]\n"
        process_cfg = ""

    os.makedirs(args.output_dir, exist_ok=True)

    # Collect unique (depth, width) pairs from IRAM and DRAM
    configs = {}
    for depth, label in [(iram_depth, "iram"), (dram_depth, "dram")]:
        key = (depth, word_size)
        if key not in configs:
            configs[key] = label

    generated = []
    for (depth, width), label in configs.items():
        name = f"sram_1rw_{depth}x{width}"
        cfg_path = os.path.join(args.output_dir, f"openram_{name}.py")
        content = make_config(
            name=name,
            num_words=depth,
            word_size=width,
            tech_name=tech_name,
            supply_voltages=supply_voltages,
            words_per_row_cfg=words_per_row_cfg,
            corner_cfg=corner_cfg,
            process_cfg=process_cfg,
            output_dir=args.output_dir,
        )
        with open(cfg_path, "w") as f:
            f.write(content)
        generated.append((name, cfg_path))
        print(f"  Wrote: {cfg_path}  ({depth} words × {width} bits)")

    print()
    print(f"Generated {len(generated)} OpenRAM config(s) in {args.output_dir}/")
    print("  Macro(s) to compile:")
    for name, _ in generated:
        print(f"    {name}")
    print()
    print("Both IRAM and DRAM byte lanes share the same macro —")
    print("jv32_top instantiates 8 copies total (4 per TCM bank).")


if __name__ == "__main__":
    main()
