#!/usr/bin/env python3
"""
gen_openram_config.py – Generate OpenRAM Python config file for jv32 TCM SRAMs.

jv32_top instantiates two 32-bit-wide TCM RAMs (IRAM and DRAM):

    sram_1rw #(.DEPTH(IRAM_DEPTH), .WIDTH(32)) u_iram  // IRAM, word-addressed
    sram_1rw #(.DEPTH(DRAM_DEPTH), .WIDTH(32)) u_dram  // DRAM, word-addressed

With the default sizes (IRAM_SIZE = DRAM_SIZE = 128 KB):

    DEPTH = 128*1024 / 4 = 32768 words,  WIDTH = 32 bits

The synthesis wrapper (syn/lib/sram_1rw.sv) implements each 32768×32 SRAM as
16 × sram_1rw_2048x32 sub-banks:

    addr[14:11] selects the sub-bank (16 banks)
    addr[10:0]  is the word address within the sub-bank (2048 rows, 11-bit decoder)

Because both IRAM and DRAM share the same (DEPTH, WIDTH) pair there is a single
OpenRAM macro to compile:  sram_1rw_2048x32

  write_size = 8  → wmask0[3:0] provides per-byte write enables (4 bytes × 8 bits)

Total instances:
    2 TCMs × 16 sub-banks = 32 sram_1rw_2048x32 macros

Usage (called by 'make gen-mem'):
    python3 common/gen_openram_config.py \\
        --iram-size 131072 --dram-size 131072 \\
        --pdk freepdk45 --output-dir lib/openram [--optimize speed|area]

Optimization targets
    speed (default) – words_per_row=1 (shortest bitlines, min sense-amp delay),
                      TT + FF + SS corners for timing sign-off.
    area            – automatic aspect-ratio; TT corner only.
"""

import argparse
import math
import os


def log2(n):
    v = int(round(math.log2(n)))
    assert (1 << v) == n, f"{n} is not a power of 2"
    return v


# sub-bank dimensions — must match the generate-block in syn/lib/sram_1rw.sv
SUB_BANK_DEPTH = 2048   # words per macro
SUB_BANK_WIDTH = 32     # bits per word
WRITE_SIZE     = 8      # bits per wmask bit (byte enables)


def make_config(name: str, num_words: int, word_size: int, write_size: int,
                tech_name: str, supply_voltages: list,
                words_per_row_cfg: str, corner_cfg: str,
                output_dir: str) -> str:
    """Return the OpenRAM Python config file content for one SRAM."""
    n_mask = word_size // write_size
    return f"""\
# OpenRAM configuration for jv32 TCM 32-bit SRAM
# Generated by gen_openram_config.py – do not edit manually.

import os

# ── SRAM dimensions ──────────────────────────────────────────────────────────
num_words       = {num_words}
word_size       = {word_size}
write_size      = {write_size}   # byte write enables: wmask0[{n_mask - 1}:0]
{words_per_row_cfg}
# ── Technology ───────────────────────────────────────────────────────────────
tech_name       = "{tech_name}"
nominal_corner_only = False
supply_voltages = {supply_voltages}
temperatures    = [25]

# ── Output ───────────────────────────────────────────────────────────────────
output_name     = "{name}"
output_path     = "."
{corner_cfg}
# ── Functional verification ───────────────────────────────────────────────────
check_lvsdrc    = False
"""


def main():
    p = argparse.ArgumentParser(
        description="Generate OpenRAM config for jv32 TCM SRAMs")
    p.add_argument("--iram-size", type=int, default=128 * 1024,
                   help="IRAM total bytes (default: 131072 = 128 KB)")
    p.add_argument("--dram-size", type=int, default=128 * 1024,
                   help="DRAM total bytes (default: 131072 = 128 KB)")
    p.add_argument("--pdk", default="freepdk45",
                   help="PDK name passed to OpenRAM (default: freepdk45)")
    p.add_argument("--output-dir", default="lib/openram",
                   help="Output directory for config files")
    p.add_argument("--optimize", choices=["speed", "area"], default="speed",
                   help="Optimization target (default: speed)")
    args = p.parse_args()

    # jv32_top uses a single 32-bit-wide SRAM per TCM, word-addressed:
    #   DEPTH = SIZE / 4   (4 bytes per 32-bit word)
    # The synthesis wrapper (syn/lib/sram_1rw.sv) decomposes each TCM into
    # SUB_BANK_DEPTH-word sub-banks with SUB_BANK_WIDTH-bit data path.
    iram_depth = args.iram_size // 4
    dram_depth = args.dram_size // 4

    # Validate: total depth must be an exact multiple of SUB_BANK_DEPTH
    for label, depth in [("IRAM", iram_depth), ("DRAM", dram_depth)]:
        assert depth % SUB_BANK_DEPTH == 0, (
            f"{label}: DEPTH={depth} is not a multiple of SUB_BANK_DEPTH={SUB_BANK_DEPTH}")
        n_banks = depth // SUB_BANK_DEPTH
        log2(n_banks)   # must be power of 2
        print(f"  {label}: {depth}×{SUB_BANK_WIDTH} → {n_banks} × "
              f"sram_1rw_{SUB_BANK_DEPTH}x{SUB_BANK_WIDTH} sub-banks")

    # PDK-specific supply
    if args.pdk == "freepdk45":
        tech_name = "freepdk45"
        supply_voltages = [1.1]
    elif args.pdk == "sky130":
        tech_name = "sky130"
        supply_voltages = [1.8]
    else:
        tech_name = args.pdk
        supply_voltages = [1.8]

    if args.optimize == "speed":
        corner_cfg = ("# Generate TT + FF + SS corners for timing sign-off\n"
                      "process_corners = [\"TT\", \"FF\", \"SS\"]\n")
    else:
        corner_cfg = "process_corners = [\"TT\"]\n"

    # words_per_row=1: shortest bitlines (min sense-amp delay), no cyclic-VCG
    # routing bug; 2048 rows → 11-bit decoder, well within OpenRAM limits.
    words_per_row_cfg = (f"words_per_row   = 1"
                         f"  # {SUB_BANK_DEPTH} rows, {log2(SUB_BANK_DEPTH)}-bit decoder\n")

    os.makedirs(args.output_dir, exist_ok=True)

    name = f"sram_1rw_{SUB_BANK_DEPTH}x{SUB_BANK_WIDTH}"
    cfg_path = os.path.join(args.output_dir, f"openram_{name}.py")
    content = make_config(
        name=name,
        num_words=SUB_BANK_DEPTH,
        word_size=SUB_BANK_WIDTH,
        write_size=WRITE_SIZE,
        tech_name=tech_name,
        supply_voltages=supply_voltages,
        words_per_row_cfg=words_per_row_cfg,
        corner_cfg=corner_cfg,
        output_dir=args.output_dir,
    )
    with open(cfg_path, "w") as f:
        f.write(content)

    n_iram = iram_depth // SUB_BANK_DEPTH
    n_dram = dram_depth // SUB_BANK_DEPTH
    print()
    print(f"Generated OpenRAM config: {cfg_path}")
    print(f"  Macro : {name}")
    print(f"  Sub-banks: {n_iram} × IRAM + {n_dram} × DRAM = "
          f"{n_iram + n_dram} instances total")
    print()
    print("Run 'make synth' to proceed to OpenLane2.")


if __name__ == "__main__":
    main()
