#!/usr/bin/env python3
"""
gen_icg_clocks.py — Regenerate the create_generated_clock block in jv32_soc_pnr.sdc
after a Yosys re-synthesis changes CLKGATE_X* instance numbers.

Usage:
    python3 syn/scripts/gen_icg_clocks.py [path/to/jv32_soc.nl.v]

Default netlist path: syn/build/openlane_run/06-yosys-synthesis/jv32_soc.nl.v

Outputs the SDC block to stdout; paste it into jv32_soc_pnr.sdc to replace
the core_clk_gck section.
"""

import re
import sys
from pathlib import Path

DEFAULT_NL = Path(__file__).resolve().parents[2] / \
    "syn/build/openlane_run/06-yosys-synthesis/jv32_soc.nl.v"

nl_path = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_NL
if not nl_path.exists():
    sys.exit(f"ERROR: netlist not found: {nl_path}")

data = nl_path.read_text()

# Build map: inst -> (cell, CK_net, GCK_net)
icg_map = {}  # inst -> dict
for m in re.finditer(r'(CLKGATE_X\d)\s+(_\d+_)\s*\(([^;]+)\)', data, re.S):
    cell, inst, body = m.group(1), m.group(2), m.group(3)
    ck_m  = re.search(r'\.CK\((\S+?)\)',  body)
    gck_m = re.search(r'\.GCK\((\S+?)\)', body)
    if ck_m and gck_m:
        icg_map[inst] = {'cell': cell, 'ck': ck_m.group(1), 'gck': gck_m.group(1)}

# Partition by CK net
core_icgs = {k: v for k, v in icg_map.items() if v['ck'] == 'clk'}
jtag_icgs = {k: v for k, v in icg_map.items() if v['ck'] == 'jtag_pin0_tck_i'}
other_icgs = {k: v for k, v in icg_map.items()
              if v['ck'] not in ('clk', 'jtag_pin0_tck_i')}

print(f"# Generated by gen_icg_clocks.py from: {nl_path.name}")
print(f"# Total CLKGATE cells: {len(icg_map)}")
print(f"#   core_clk domain (CK=clk):              {len(core_icgs)}")
print(f"#   jtag_tck domain (CK=jtag_pin0_tck_i):  {len(jtag_icgs)}")
if other_icgs:
    print(f"#   other CK nets:                         {len(other_icgs)}")
    for inst, v in sorted(other_icgs.items()):
        print(f"#     {v['cell']} {inst}: CK={v['ck']}")
print()

if core_icgs:
    pins = sorted(f"{inst}/GCK" for inst in core_icgs)
    # Format in rows of 5
    rows = [pins[i:i+5] for i in range(0, len(pins), 5)]
    pin_lines = "\n               ".join(" ".join(r) for r in rows)
    print("create_generated_clock -name core_clk_gck \\")
    print("    -source [get_ports clk] -master_clock core_clk \\")
    print(f"    [get_pins {{{pin_lines}}}]")
    print()

if jtag_icgs:
    # jtag domain ICGs: OpenSTA should auto-propagate via liberty, but print
    # the list as a comment for reference.
    pins = sorted(f"{inst}/GCK" for inst in jtag_icgs)
    print("# jtag_tck domain ICG GCK pins (auto-propagated by liberty):")
    for p in pins:
        print(f"#   {p}")
    print()
