#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# hier_synth.sh — Standalone Yosys hierarchical synthesis for gate-count.
#
# Synthesises jv32_soc WITHOUT flattening so stat.json contains per-module
# gate counts used by gen_gate_count.py.
#
# Must be executed inside the OpenLane nix-shell (which provides Yosys):
#   nix-shell shell.nix --run "bash hier_synth.sh"
#
# Required environment variables:
#   NANGATE_LIB  — path to NangateOpenCellLibrary_typical.lib
#   STAT_JSON    — output path for stat.json
#   RTL_DIR      — absolute path to the rtl/ directory
#   LIB_DIR      — absolute path to syn/lib/ directory
#   IRAM_SIZE    — IRAM bytes (e.g. 16384)
#   DRAM_SIZE    — DRAM bytes (e.g. 16384)
#   FAST_MUL, MUL_MC, FAST_DIV, FAST_SHIFT, BP_EN  — pipeline feature bits
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

: "${NANGATE_LIB:?NANGATE_LIB must be set}"
: "${STAT_JSON:?STAT_JSON must be set}"
: "${RTL_DIR:?RTL_DIR must be set}"
: "${LIB_DIR:?LIB_DIR must be set}"
: "${IRAM_SIZE:=16384}"
: "${DRAM_SIZE:=16384}"
: "${FAST_MUL:=1}"
: "${MUL_MC:=1}"
: "${FAST_DIV:=0}"
: "${FAST_SHIFT:=1}"
: "${BP_EN:=1}"

STAT_DIR="$(dirname "$STAT_JSON")"
mkdir -p "$STAT_DIR"

YS_SCRIPT="$(mktemp /tmp/hier_synth_XXXXXX.ys)"
trap 'rm -f "$YS_SCRIPT"' EXIT

# ─────────────────────────────────────────────────────────────────────────────
# Generate the Yosys script with all paths and parameters substituted.
# ─────────────────────────────────────────────────────────────────────────────
cat > "$YS_SCRIPT" << YOSYS_EOF
# Hierarchical synthesis for jv32_soc — generated by hier_synth.sh
# Uses the synlig-sv (Surelog) plugin to handle full SystemVerilog (import, packages).
# Yosys 'synth' does NOT flatten by default; module boundaries are preserved.

# ── Load Surelog/Synlig SystemVerilog frontend ───────────────────────────────
plugin -i synlig-sv

YOSYS_EOF

# Build read_systemverilog as a single long line (synlig non-deferred mode).
# All files are compiled in one Surelog session, so includes/macros are shared.
{
    printf 'read_systemverilog -sverilog -top jv32_soc'
    printf ' -DSYNTHESIS -DNO_ASSERTION -DGENERIC_SRAM'
    printf ' -I%s' "${RTL_DIR}/jv32"
    printf ' -PIRAM_SIZE=%s -PDRAM_SIZE=%s' "${IRAM_SIZE}" "${DRAM_SIZE}"
    printf ' -PFAST_MUL=%s -PMUL_MC=%s -PFAST_DIV=%s -PFAST_SHIFT=%s -PBP_EN=%s' \
        "${FAST_MUL}" "${MUL_MC}" "${FAST_DIV}" "${FAST_SHIFT}" "${BP_EN}"
    printf ' %s' \
        "${RTL_DIR}/jv32/core/jv32_pkg.sv" \
        "${RTL_DIR}/jv32/core/jv32_rvc.sv" \
        "${RTL_DIR}/jv32/core/jv32_decoder.sv" \
        "${RTL_DIR}/jv32/core/jv32_alu.sv" \
        "${RTL_DIR}/jv32/core/jv32_regfile.sv" \
        "${RTL_DIR}/jv32/core/jv32_csr.sv" \
        "${RTL_DIR}/jv32/core/jv32_core.sv" \
        "${RTL_DIR}/jv32/core/jtag/cjtag_bridge.sv" \
        "${RTL_DIR}/jv32/core/jtag/jv32_dtm.sv" \
        "${RTL_DIR}/jv32/core/jtag/jtag_tap.sv" \
        "${RTL_DIR}/jv32/core/jtag/jtag_top.sv" \
        "${LIB_DIR}/sram_1rw.sv" \
        "${RTL_DIR}/axi/axi_pkg.sv" \
        "${RTL_DIR}/axi/axi_xbar.sv" \
        "${RTL_DIR}/axi/axi_uart.sv" \
        "${RTL_DIR}/axi/axi_clic.sv" \
        "${RTL_DIR}/axi/axi_ram_ctrl.sv" \
        "${RTL_DIR}/axi/axi_magic.sv" \
        "${RTL_DIR}/jv32/jv32_top.sv" \
        "${RTL_DIR}/jv32_soc.sv"
    printf '\n'
} >> "$YS_SCRIPT"

cat >> "$YS_SCRIPT" << YOSYS_EOF

# ── Synthesise without flattening ────────────────────────────────────────────
# 'synth -top' does NOT flatten module hierarchy by default.
synth -top jv32_soc

# ── Technology mapping ───────────────────────────────────────────────────────
dfflibmap -liberty ${NANGATE_LIB}
abc -liberty ${NANGATE_LIB}
clean

# ── Hierarchical gate statistics ─────────────────────────────────────────────
tee -o ${STAT_JSON} stat -json -liberty ${NANGATE_LIB}
YOSYS_EOF

echo "========================================================"
echo " Yosys hierarchical synthesis (no flatten)"
echo "  Liberty : ${NANGATE_LIB}"
echo "  Output  : ${STAT_JSON}"
echo "========================================================"

yosys -l "${STAT_JSON%.json}.log" "$YS_SCRIPT"

echo ""
echo "Synthesis complete."
echo "  stat.json : ${STAT_JSON}"
echo "  log       : ${STAT_JSON%.json}.log"
