LDFLAGS_EXTRA += -nostdlib
CFLAGS += -DEXPECT_A=$(if $(AMO_EN),$(AMO_EN),1)
CFLAGS += -DEXPECT_M=$(if $(RV32M_EN),$(RV32M_EN),1)
CFLAGS += -DEXPECT_B=$(if $(RV32B_EN),$(RV32B_EN),1)
CFLAGS += -DEXPECT_ZCMP=$(if $(ZCMP_EN),$(ZCMP_EN),1)
